name: Jeff Sensat
favicon: null
layout_spectrum: 0.9349838707130402
typography_spectrum: 0.7745518451556563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4188221604563296
  lightness: 0.3210326852276921
  saturation: 0.2800532579421997
  rhythmicContrast: 0.29167166957631707
purpose: []
